### ISSUE TITLE
Gift Card: Cannot compile Admin UI with Vendure V2 

### ISSUE THREAD

**Issue by PKarics** [vendure-ecommerce/vendure-plus-issues#16]
[gift-card-admin-ui-compile-errors.txt](https://github.com/vendure-ecommerce/vendure-plus-issues/files/11271729/gift-card-admin-ui-compile-errors.txt)

**Comment by michaelbromley** [comment]
Thanks for the report. Please try the newly-publish v1.0.0-next.0
