### ISSUE TITLE
Installing in CI doesn't work

### ISSUE THREAD

**Issue by JamesLAllen** [vendure-ecommerce/vendure-plus-issues#28]
The example says we need to generate an npm api key and then generate the .npmrc file with the `authToken` and then run `npm install`, however this doesn't work.  Everything is also installed using `yarn` and so we don't want to mix our installation methods.  Is there an example of CI running that doesn't require a manual `adduser` and login step?

**Comment by JamesLAllen** [comment]
I think the documentation can be a little clearer for CI, it wasn't fully clear that we would get the authToken from ~/.npmrc and instead I assumed we had to generate our authToken on NPM and use that.

**Comment by michaelbromley** [comment]
Hi James, thanks for the feedback. Currently we have this in the readme:

> The value of VENDURE_PLUS_AUTH_TOKEN can be found in your local ~/.npmrc file after logging in following the instructions above. 

What do you suggest we could do to make it clearer or help people avoid frustration?

**Comment by JamesLAllen** [comment]
Yes, I would add a final step in the Setup Instructions to find and save the VENDURE_PLUS_AUTH_TOKEN from the ~/.npmrc and then move this line:

"This is covered in the npm docs [Using private packages in a CI/CD workflow](https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow)."

down to the bottom and rework it to be something like:

"More information on this process can be found in the npm docs [Using private packages in a CI/CD workflow](https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow)."

For me, I did the initial setup, and then I followed the link to the CI instructions on npm, and followed those instructions thinking that it would work, ie I created my own API Key, not realizing that a key for the private repo had already been generated for me in my own npmrc.  I even cleared my npm cache several times, thinking that a CI/CD wouldn't require me to log in first, therefore I thought my API key wasn't working for some reason.
