### ISSUE TITLE
Advanced Search - x-typesense-api-key error when connecting with additional server

### ISSUE THREAD

**Issue by JamesLAllen** [vendure-ecommerce/vendure-plus-issues#31]
When starting up a new server, it causes the existing server to lose its connection because the all keys are deleted and a new key generated for the new server, even if using the same `TYPESENSE_SHOP_API_KEY_SECRET`.

**Comment by michaelbromley** [comment]
Hi,

Can you share the startup logs when this occurs? Specifically, when keys get deleted it should log

```
Deleted redundant Shop API key with ID ${id}
```

Are you seeing this?

Can you also confirm that your DB has the custom field `advancedSearchShopApiKeys` added on the global_settings table?

**Comment by JamesLAllen** [comment]
I have a hypothesis that one of the devs on our team connected to our typesense on DEV but was still referencing the local database.  Perhaps there's an error that can be thrown when a system starts and there is a mismatch of fields, instead of just deleting the keys and creating new ones?

**Comment by michaelbromley** [comment]
This is resolved in v1.6.1
